Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,3 +38,43 @@ jobs:
 
     - name: Run tests
       run: npm test
+      
+  lighthouse:
+    runs-on: ubuntu-latest
+    needs: test # 어떠한 job이 실행되어야 실행한다.
+    
+    steps:
+    - name: checkout code
+      uses : actions/checkout@v4
+
+    - name: Setup Node.js # Step 이름
+      uses: actions/setup-node@v4 # 라이브러리 이름
+      with:  # 라이브러리 정보
+        node-version: '20.x'
+        registry-url: 'https://registry.npmjs.org'
+        
+    - name: Configure npm registry
+      run: |
+        echo "Configuring npm to use public registry"
+        npm config set registry https://registry.npmjs.org/
+
+    - name: Clear npm cache
+      run: npm cache clean --force
+
+    - name: Remove package-lock.json
+      run: rm -f package-lock.json
+      
+    - name: Install dependencies
+      run: npm install --registry=https://registry.npmjs.org/
+      env:
+        NODE_AUTH_TOKEN: ''
+
+    - name: Build project
+      run: npm run build
+
+    - name: Run Lighthouse CI
+      env:
+        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+      run: |
+        npm install -g @lhci/cli
+        lhci autorun || echo "Fail to Run Lighthouse CI!"
